name: ci
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install CBC solver
        run: sudo apt-get update && sudo apt-get install -y coinor-cbc

      - name: Install Python deps
        run: python -m pip install -r requirements.txt

      - name: Smoke test pipeline (fast)
        run: |
          python -m src.sim_data --weeks 12 --seed 7
          python -m src.forecast --horizon 4
          python -m src.allocation --horizon 4 --supply_ratio 0.9 --min_service 0.85
          python -m src.metrics_and_plots --horizon 4 --min_service 0.85
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/*.png
            reports/*.csv
